// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"github.com/dathuynh1108/clean-arch-base/internal/v1/usecase"
)

// Injectors from wire.go:

func ProvideHealthController() *HealthControler {
	healthUsecase := usecase.ProvideHealthUsecase()
	healthControler := NewHealthController(healthUsecase)
	return healthControler
}

func ProvideWSController() *WSController {
	wsController := NewWSController()
	return wsController
}

func ProvideErrorController() *ErrorControler {
	errorControler := NewErrorController()
	return errorControler
}
