// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"github.com/dathuynh1108/clean-arch-base/internal/v1/usecase"
)

// Injectors from wire.go:

func ProvideHealthController() *HealthController {
	healthUsecase := usecase.ProvideHealthUsecase()
	healthController := NewHealthController(healthUsecase)
	return healthController
}

func ProvideErrorController() *ErrorController {
	errorController := NewErrorController()
	return errorController
}
