[server]
host = "0.0.0.0"
port = "8080"

[redis]
addrs = "0.0.0.0:6379"
db = "0"
username = ""
password = ""


[[databases.default]]
engine = "mysql"
host = "localhost"
port = "3306"
user = "user1"
pass = "pass1"
database = "db1"
instance = "master"

[[databases.default]]
engine = "postgresql"
host = "localhost"
port = "3306"
user = "user1"
pass = "pass1"
database = "db2"
instance = "master"

[[databases.default]]
engine = "mysql"
host = "localhost"
port = "3306"
user = "user1"
pass = "pass1"
database = "db1"
instance = "master"

[[databases.default]]
engine = "postgresql"
host = "localhost"
port = "3306"
user = "user1"
pass = "pass1"
database = "db2"
instance = "master"

[logger]
level = "debug"
file_path = "./logs/server.log"
format = "text"


