// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repository

import (
	"github.com/dathuynh1108/clean-arch-base/pkg/database"
	"github.com/dathuynh1108/clean-arch-base/pkg/database/dbpool"
	"github.com/dathuynh1108/clean-arch-base/pkg/database/repo"
)

// Injectors from wire.go:

func ProvideHealthRepo() repo.RepoRouter[HealthRepo] {
	dbAlias := ProvideDBAliasDefault()
	dbPool := database.GetDBPool()
	repositoryHealthRepoRouter := NewHealthRepoRouter(dbAlias, dbPool)
	return repositoryHealthRepoRouter
}

// wire.go:

func ProvideDBAliasDefault() dbpool.DBAlias {
	return dbpool.DBDefault
}
